return {
    -- "nvim-neo-tree/neo-tree.nvim",
    -- branch = "v3.x",
    -- dependencies = {
    --     "nvim-lua/plenary.nvim",
    --     "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
    --     "MunifTanjim/nui.nvim",
    --     -- "3rd/image.nvim", -- Optional image support in preview window: See `# Preview Mode` for more information
    -- },
    -- config = function()
    --     require("neo-tree").setup({
    --         filesystem = {
    --             follow_current_file = {
    --                 enabled = true,
    --             },
    --             hijack_netrw_behavior = "disabled", -- netrw disabled, opening a directory opens neo-tree
    --             -- in whatever position is specified in window.position
    --             -- "open_current",  -- netrw disabled, opening a directory opens within the
    --             -- window like netrw would, regardless of window.position
    --             -- "disabled",    -- netrw left alone, neo-tree does not handle opening dirs
    --         },
    --     })
    -- end
}
